### PR TITLE
Update Global Rs csv records

### PR DESCRIPTION
**Pull request by jinshijian**
Added few data into the data.

### CODE REVIEW

**Comment by jinshijian** [comment]
Update the dataset,another issue is that there are duplicate in Zhao et al (2017) and Peng et al (2000).

**Comment by bpbond** [comment]
Thanks @jinshijian ! The code you added doesn't have a definition for `do_sim` that's called in line 145 or so:
```r
results <- mclapply(seq_len(n_sims), do_sim, respdata, error = median_error)
```
Do you have that? Though I'm sure I can find it too.

**Comment by jinshijian** [comment]
do_sim <- function(i, respdata, error = 0.0) {
  # This is observational error
  respdata$Resp_fuzz <- fuzz(respdata$Resp_iav, error)
  respdata$trend_p <- trend_emergence(respdata$Resp_fuzz)
  respdata
}

**Comment by jinshijian** [comment]
do_sim <- function(i, respdata, error = 0.0) {
  # This is observational error
  respdata$Resp_fuzz <- fuzz(respdata$Resp_iav, error)
  respdata$trend_p <- trend_emergence(respdata$Resp_fuzz)
  respdata
}

**Pull request merged**
